[package]
name = "interceptor-dev"
version = "0.1.0"
edition = "2024"

[dependencies]
clap-config-file = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
config = "0.14"
bollard = "0.21.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
futures-util = "0.3"
chrono = "0.4"
serde_json = "1"
toml = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json"] }
tokio-util = { version = "0.7", features = ["rt"] }
tendermint-p2p = "=0.40.4"
tendermint-proto = "=0.40.4"
ed25519-consensus = "2"
prost = "0.13"
base64 = "0.22"
sha2 = "0.10"
hex = "0.4"
